package example.jbot.slack;

import java.util.HashMap;
import java.util.Map;

public class Elements {
	public Map<String, String> elements = new HashMap<String, String>();

	public void LoadElements() {
		elements.put("Hydrogen", "Element Symbol: H. Hydrogen is the first element of the periodic table. ");
		elements.put("Helium", "Element Symbol: He. Helium is the second element of the periodic table. ");
		elements.put("Lithium", "Element Symbol: Li. Lithium is the third element of the periodic table. ");
		elements.put("Beryllium", "Element Symbol: Be. Beryllium is the fourth element of the periodic table. ");
		elements.put("Boron", "Element Symbol: B. Boron is the fifth element of the periodic table. ");
		elements.put("Carbon", "Element Symbol: C. Carbon is the sixth element of the periodic table. ");
		elements.put("Nitrogen", "Element Symbol: N. Nitrogen is the seventh element of the periodic table. ");
		elements.put("Oxygen", "Element Symbol: O. Oxygen is the eigth of the periodic table. ");
		elements.put("Fluorine", "Element Symbol: F. Fluorine is the ninth element of the periodic table. ");
		elements.put("Neon", "Element Symbol: Ne. Neon is the tenth of the periodic table. ");
		elements.put("Sodium", "Element Symbol: Na. Sodium is the 11th element of the periodic table. ");
		elements.put("Magnesium", "Element Symbol: Mg. Magnesium is the 12th element of the periodic table. "); // Inputing all of these took forever, appreciate my work.
		elements.put("Aluminum", "Element Symbol: Al. Aluminum is the 13th element of the periodic table. ");
		elements.put("Silicon", "Element Symbol: Si. Silicon is the 14th element of the periodic table. ");
		elements.put("Phosphorus", "Element Symbol: P. Phosphorus is the 15th element of the periodic table. ");
		elements.put("Sulfur", "Element Symbol: S. Sulfur is the 16th element of the periodic table. ");
		elements.put("Chlorine", "Element Symbol: Ci. Chlorine is the 17th element of the periodic table. ");
		elements.put("Argon", "Element Symbol: Ar. Argon is the 18th element of the periodic table. ");
		elements.put("Potassium	", "Element Symbol: K. Potassium is the 19th element of the periodic table. ");
		elements.put("Scandium", "Element Symbol: Sc. Scandium is the 20th element of the periodic table. ");
		elements.put("Titanium", "Element Symbol: Ti. Titanium is the 21st element of the periodic table. ");
		elements.put("Vanadium", "Element Symbol: V. Vanadium is the 22nd element of the periodic table. ");
		elements.put("Chromium", "Element Symbol: Cr. Chromium is the 23rd element of the periodic table. ");
		elements.put("Manganese", "Element Symbol: Mn. Manganese is the 24th element of the periodic table. ");
		elements.put("Iron", "Element Symbol: Fe. Iron is the 25th element of the periodic table. ");
		elements.put("Cobalt", "Element Symbol: Co. Cobalt is the 26th element of the periodic table. ");
		elements.put("Nickel", "Element Symbol: Ni. Nickel is the 27th element of the periodic table. ");
		elements.put("Copper", "Element Symbol: Cu. Copper is the 28th element of the periodic table. ");
		elements.put("Zinc", "Element Symbol: Zn. Zinc is the 29th element of the periodic table. ");
		elements.put("Gallium", "Element Symbol: Ga. Gallium is the 30th element of the periodic table. ");
		elements.put("Germanium", "Element Symbol: Ge. Germanium is the 31st element of the periodic table. ");
		elements.put("Arsenic", "Element Symbol: As. Arsenic is the 32nd element of the periodic table. ");
		elements.put("Selenium", "Element Symbol: Se. Selenium is the 33rd element of the periodic table. ");
		elements.put("Bromine", "Element Symbol: Br. Bromine is the 34th element of the periodic table. ");
		elements.put("Krypton", "Element Symbol: Kr. Krypton is the 35th element of the periodic table. ");
		elements.put("Rubidium", "Element Symbol: Rb. Rubidium is the 36th element of the periodic table. ");
		elements.put("Strontium", "Element Symbol: Sr. Strontium is the 37th element of the periodic table. ");
		elements.put("Yttrium", "Element Symbol: Y. Yttrium is the 38th element of the periodic table. ");
		elements.put("Zirconium", "Element Symbol: Zr. Zirconium is the 39th element of the periodic table. ");
		elements.put("Niobium", "Element Symbol: Nb. Niobium is the 40th element of the periodic table. ");
		elements.put("Molybdenum", "Element Symbol: Mo. Molybdenum is the 41st element of the periodic table. ");
		elements.put("Technetium", "Element Symbol: Tc. Technetium is the 42nd element of the periodic table. ");
		elements.put("Ruthenium", "Element Symbol: Ru. Ruthenium is the 43rd element of the periodic table. ");
		elements.put("Rhodium", "Element Symbol: Rh. Rhodium is the first 44th of the periodic table. ");
		elements.put("Palladium", "Element Symbol: Pd. Palladium is the 45th element of the periodic table. ");
		elements.put("Silver", "Element Symbol: Ag. Silver is the 46th element of the periodic table. ");
		elements.put("Cadmium", "Element Symbol: Cd. Cadmium is the 47th element of the periodic table. ");
		elements.put("Indium", "Element Symbol: Id. Indium is the 48th element of the periodic table. ");
		elements.put("Tin", "Element Symbol: Sn. Tin is the 49th element of the periodic table. ");
		elements.put("Antimony", "Element Symbol: Sb. Antimony is the 50th element of the periodic table. ");
		elements.put("Tellurium", "Element Symbol: Te. Tellurium is the 51st element of the periodic table. ");
		elements.put("Iodine", "Element Symbol: I. Iodine is the 52nd element of the periodic table. ");
		elements.put("Xenon", "Element Symbol: Xe. Xenon is the 53rd element of the periodic table. ");
		elements.put("Cesium", "Element Symbol: Cs. Cesium is the 54th element of the periodic table. ");
		elements.put("Barium", "Element Symbol: Ba. Barium is the 55th element of the periodic table. ");
		elements.put("Lanthanum", "Element Symbol: La. Lanthanum is the 56th element of the periodic table. ");
		elements.put("Cerium", "Element Symbol: Ce. Cerium is the 57th element of the periodic table. ");
		elements.put("Praseodymium", "Element Symbol: Pr. Praseodymium is the 58th element of the periodic table. ");
		elements.put("Neodymium", "Element Symbol: Nd. Neodymium is the 59th element of the periodic table. ");
		elements.put("Promethium", "Element Symbol: Pm. Promethium is the 60th element of the periodic table. ");
		elements.put("Samarium", "Element Symbol: Sm. Samarium is the 61st element of the periodic table. ");
		elements.put("Europium", "Element Symbol: Eu. Europium is the 62nd element of the periodic table. ");
		elements.put("Gadolinium", "Element Symbol: Gd. Gadolinium is the 63rd element of the periodic table. ");
		elements.put("Terbium", "Element Symbol: Tb. Terbium is the 64th element of the periodic table. ");
		elements.put("Dysprosium", "Element Symbol: Dy. Dysprosium is the 65th element of the periodic table. ");
		elements.put("Holmium", "Element Symbol: Ho. Holmium is the 66th element of the periodic table. ");
		elements.put("Erbium", "Element Symbol: Er. Erbium is the 67th element of the periodic table. ");
		elements.put("Thulium", "Element Symbol: Tm. Thulium is the 68th element of the periodic table. ");
		elements.put("Ytterbium", "Element Symbol: Yb. Ytterbium is the 69th (haha) element of the periodic table. ");
		elements.put("Lutetium", "Element Symbol: Lu. Lutetium is the 70th element of the periodic table. ");
		elements.put("Hafnium", "Element Symbol: Hf. Hafnium is the 71st element of the periodic table. ");
		elements.put("Tantalum", "Element Symbol: Ta. Tantalum is the 72nd element of the periodic table. ");
		elements.put("Tungsten", "Element Symbol: W. Tungsten is the 73rd element of the periodic table. ");
		elements.put("Rhenium", "Element Symbol: Re. Rhenium is the 74th element of the periodic table. ");
		elements.put("Osmium", "Element Symbol: Os. Osmium is the 75th element of the periodic table. ");
		elements.put("Iridium", "Element Symbol: Ir. Iridium is the 76th element of the periodic table. ");
		elements.put("Platinum", "Element Symbol: Pt. Platinum is the 77th element of the periodic table. ");
		elements.put("Gold", "Element Symbol: Au. Gold is the 78th element of the periodic table. ");
		elements.put("Mercury", "Element Symbol: Hg. Mercury is the 79th element of the periodic table. ");
		elements.put("Thallium", "Element Symbol: Tl. Thallium is the 80th element of the periodic table. ");
		elements.put("Lead", "Element Symbol: Pb. Lead is the 81st element of the periodic table. ");
		elements.put("Bismuth", "Element Symbol: Bi. Bismuth is the 82nd element of the periodic table. ");
		elements.put("Polonium", "Element Symbol: Po. Polonium is the 83rd element of the periodic table. ");
		elements.put("Astatine", "Element Symbol: At. Astatine is the 84th element of the periodic table. ");
		elements.put("Radon", "Element Symbol: Rn. Radon is the 85th element of the periodic table. ");
		elements.put("Francium", "Element Symbol: Fr. Francium is the 86th element of the periodic table. ");
		elements.put("Radium", "Element Symbol: Ra. Radium is the 87th element of the periodic table. ");
		elements.put("Actinium", "Element Symbol: Ac. Actinium is the 88th element of the periodic table. ");
		elements.put("Thorium", "Element Symbol: Th. Thorium is the 89th element of the periodic table. ");
		elements.put("Protactinium", "Element Symbol: Pa. Protactinium is the 90th element of the periodic table. ");
		elements.put("Uranium", "Element Symbol: U. Uranium is the 91st element of the periodic table. ");
		elements.put("Neptunium", "Element Symbol: Np. Neptunium is the 92nd element of the periodic table. ");
		elements.put("Plutonium", "Element Symbol: Pu. Plutonium is the 93rd element of the periodic table. ");
		elements.put("Americium", "Element Symbol: Am. Americium is the 94th element of the periodic table. ");
		elements.put("Curium", "Element Symbol: Cm. Curium is the 95th element of the periodic table. ");
		elements.put("Berkelium", "Element Symbol: Bk. Berkelium is the 96th element of the periodic table. ");
		elements.put("Californium", "Element Symbol: Cf. Californium is the 97th element of the periodic table. ");
		elements.put("Einsteinium", "Element Symbol: Es. Einsteinium is the 98th element of the periodic table. ");
		elements.put("Fermium", "Element Symbol: Fm. Fermium is the 99th element of the periodic table. ");
		elements.put("Mendelevium", "Element Symbol: Md. Mendelevium is the 100th element of the periodic table. ");
		elements.put("Nobelium", "Element Symbol: No. Nobelium is the 101st element of the periodic table. ");
		elements.put("Lawrencium", "Element Symbol: Lr. Lawrencium is the 102nd element of the periodic table. ");
		elements.put("Rutherfordium", "Element Symbol: Rf. Rutherfordium is the 103rd element of the periodic table. ");
		elements.put("Dubnium", "Element Symbol: Db. Dubnium is the 104th element of the periodic table. ");
		elements.put("Seaborgium", "Element Symbol: Sg. Seaborgium is the 105th element of the periodic table. ");
		elements.put("Bohrium", "Element Symbol: Bh. Bohrium is the 106th element of the periodic table. ");
		elements.put("Hassium", "Element Symbol: Hs. Hassium is the 107th element of the periodic table. ");
		elements.put("Meitnerium", "Element Symbol: Mt. Meitnerium is the 108th element of the periodic table. ");
		elements.put("Darmstadtium", "Element Symbol: Ds. Darmstadtium is the 109th element of the periodic table. ");
		elements.put("Roentgenium", "Element Symbol: Rg. Roentgenium is the 110th element of the periodic table. ");
		elements.put("Ununbium", "Element Symbol: Uub. Ununbium is the first 111th of the periodic table. ");
		elements.put("Ununtrium", "Element Symbol: Uut. Ununtrium is the 112th element of the periodic table. ");
		elements.put("Ununquadium", "Element Symbol: Uuq. Ununquadium is the 113th element of the periodic table. ");
		elements.put("Ununpentium", "Element Symbol: Uup. Ununpentium is the 114th element of the periodic table. ");
		elements.put("Ununhexium", "Element Symbol: Uuh. Ununhexium is the 115th element of the periodic table. ");
		elements.put("Ununseptium", "Element Symbol: Uus. Ununseptium is the 116th element of the periodic table. ");
		elements.put("Ununoctium", "Element Symbol: Uuo. Ununoctium is the 117th element of the periodic table. ");

	}

}
