package example.jbot.slack;

import java.util.HashMap;
import java.util.Map;

public class Elements {
	public Map<String, String> elements = new HashMap<String, String>();

	public void LoadElements() {
		elements.put("Hydrogen", "Element Symbol: H. Hydrogen is the first element of the periodic table. ");
		elements.put("Helium", "works");
		elements.put("Lithium", "works");
		elements.put("Beryllium", "works");
		elements.put("Boron", "works");
		elements.put("Carbon", "works");
		elements.put("Nitrogen", "works");
		elements.put("Oxygen", "works");
		elements.put("Fluorine", "works");
		elements.put("Neon", "works");
		elements.put("Sodium", "works");
		elements.put("Magnesium", "works"); //Editing this to confirm it works.
		elements.put("Aluminum", "works");
		elements.put("Silicon", "works");
		elements.put("Phosphorus", "works");
		elements.put("Sulfur", "works");
		elements.put("Chlorine", "works");
		elements.put("Argon", "works");
		elements.put("Potassium	", "works");
		elements.put("Scandium", "works");
		elements.put("Titanium", "works");
		elements.put("Vanadium", "works");
		elements.put("Chromium", "works");
		elements.put("Manganese", "works");
		elements.put("Iron", "works");
		elements.put("Cobalt", "works");
		elements.put("Nickel", "works");
		elements.put("Copper", "works");
		elements.put("Zinc", "works");
		elements.put("Gallium", "works");
		elements.put("Germanium", "works");
		elements.put("Arsenic", "works");
		elements.put("Selenium", "works");
		elements.put("Bromine", "works");
		elements.put("Krypton", "works");
		elements.put("Rubidium", "works");
		elements.put("Strontium", "works");
		elements.put("Yttrium", "works");
		elements.put("Zirconium", "works");
		elements.put("Niobium", "works");
		elements.put("Molybdenum", "works");
		elements.put("Technetium", "works");
		elements.put("Ruthenium", "works");
		elements.put("Rhodium", "works");
		elements.put("Palladium", "works");
		elements.put("Silver", "works");
		elements.put("Cadmium", "works");
		elements.put("Indium", "works");
		elements.put("Tin", "works");
		elements.put("Antimony", "works");
		elements.put("Tellurium", "works");
		elements.put("Iodine", "works");
		elements.put("Xenon", "works");
		elements.put("Cesium", "works");
		elements.put("Barium", "works");
		elements.put("Lanthanum", "works");
		elements.put("Cerium", "works");
		elements.put("Praseodymium", "works");
		elements.put("Neodymium", "works");
		elements.put("Promethium", "works");
		elements.put("Samarium", "works");
		elements.put("Europium", "works");
		elements.put("Gadolinium", "works");
		elements.put("Terbium", "works");
		elements.put("Dysprosium", "works");
		elements.put("Holmium", "works");
		elements.put("Erbium", "works");
		elements.put("Thulium", "works");
		elements.put("Ytterbium", "works");
		elements.put("Lutetium", "works");
		elements.put("Hafnium", "works");
		elements.put("Tantalum", "works");
		elements.put("Tungsten", "works");
		elements.put("Rhenium", "works");
		elements.put("Osmium", "works");
		elements.put("Iridium", "works");
		elements.put("Platinum", "works");
		elements.put("Gold", "works");
		elements.put("Mercury", "works");
		elements.put("Thallium", "works");
		elements.put("Lead", "works");
		elements.put("Bismuth", "works");
		elements.put("Polonium", "works");
		elements.put("Astatine", "works");
		elements.put("Radon", "works");
		elements.put("Francium", "works");
		elements.put("Radium", "works");
		elements.put("Actinium", "works");
		elements.put("Thorium", "works");
		elements.put("Protactinium", "works");
		elements.put("Uranium", "works");
		elements.put("Neptunium", "works");
		elements.put("Plutonium", "works");
		elements.put("Americium", "works");
		elements.put("Curium", "works");
		elements.put("Berkelium", "works");
		elements.put("Californium", "works");
		elements.put("Einsteinium", "Is named after theoretical physicist Albert Einstien");
		elements.put("Fermium", "works");
		elements.put("Mendelevium", "works");
		elements.put("Nobelium", "works");
		elements.put("Lawrencium", "works");
		elements.put("Rutherfordium", "works");
		elements.put("Dubnium", "works");
		elements.put("Seaborgium", "works");
		elements.put("Bohrium", "works");
		elements.put("Hassium", "works");
		elements.put("Meitnerium", "works");
		elements.put("Darmstadtium", "works");
		elements.put("Roentgenium", "works");
		elements.put("Ununbium", "works");
		elements.put("Ununtrium", "works");
		elements.put("Ununquadium", "works");
		elements.put("Ununpentium", "works");
		elements.put("Ununhexium", "works");
		elements.put("Ununseptium", "works");
		elements.put("Ununoctium", "works");

	}

}
