package example.jbot.slack;

import java.util.HashMap;
import java.util.Map;

public class Elements {
	public Map<String, String> elements = new HashMap<String, String>();

	public void LoadElements() {
		elements.put("Hydrogen", "Element Symbol: H. Hydrogen is the first element of the periodic table. ");
		elements.put("Helium", "Element Symbol: He. Helium is the second element of the periodic table. ");
		elements.put("Lithium", "Element Symbol: Li. Lithium is the third element of the periodic table. ");
		elements.put("Beryllium", "Element Symbol: H. Beryllium is the fourth element of the periodic table. ");
		elements.put("Boron", "Element Symbol: H. Boron is the fifth element of the periodic table. ");
		elements.put("Carbon", "Element Symbol: H. Carbon is the sixth element of the periodic table. ");
		elements.put("Nitrogen", "Element Symbol: H. Nitrogen is the seventh element of the periodic table. ");
		elements.put("Oxygen", "Element Symbol: H. Oxygen is the eigth of the periodic table. ");
		elements.put("Fluorine", "Element Symbol: H. Fluorine is the ninth element of the periodic table. ");
		elements.put("Neon", "Element Symbol: H. Neon is the tenth of the periodic table. ");
		elements.put("Sodium", "Element Symbol: H. Sodium is the 11th element of the periodic table. ");
		elements.put("Magnesium", "Element Symbol: H. Magnesium is the 12th element of the periodic table. "); // Inputing all of these took forever, appreciate my work.
		elements.put("Aluminum", "Element Symbol: H. Aluminum is the 13th element of the periodic table. ");
		elements.put("Silicon", "Element Symbol: H. Silicon is the 14th element of the periodic table. ");
		elements.put("Phosphorus", "Element Symbol: H. Phosphorus is the 15th element of the periodic table. ");
		elements.put("Sulfur", "Element Symbol: H. Sulfur is the 16th element of the periodic table. ");
		elements.put("Chlorine", "Element Symbol: H. Chlorine is the 17th element of the periodic table. ");
		elements.put("Argon", "Element Symbol: H. Argon is the 18th element of the periodic table. ");
		elements.put("Potassium	", "Element Symbol: H. Potassium is the 19th element of the periodic table. ");
		elements.put("Scandium", "Element Symbol: H. Scandium is the 20th element of the periodic table. ");
		elements.put("Titanium", "Element Symbol: H. Titanium is the 21st element of the periodic table. ");
		elements.put("Vanadium", "Element Symbol: H. Vanadium is the 22nd element of the periodic table. ");
		elements.put("Chromium", "Element Symbol: H. Chromium is the 23rd element of the periodic table. ");
		elements.put("Manganese", "Element Symbol: H. Manganese is the 24th element of the periodic table. ");
		elements.put("Iron", "Element Symbol: H. Iron is the 25th element of the periodic table. ");
		elements.put("Cobalt", "Element Symbol: H. Cobalt is the 26th element of the periodic table. ");
		elements.put("Nickel", "Element Symbol: H. Nickel is the 27th element of the periodic table. ");
		elements.put("Copper", "Element Symbol: H. Copper is the 28th element of the periodic table. ");
		elements.put("Zinc", "Element Symbol: H. Zinc is the 29th element of the periodic table. ");
		elements.put("Gallium", "Element Symbol: H. Gallium is the 30th element of the periodic table. ");
		elements.put("Germanium", "Element Symbol: H. Germanium is the 31st element of the periodic table. ");
		elements.put("Arsenic", "Element Symbol: H. Arsenic is the 32nd element of the periodic table. ");
		elements.put("Selenium", "Element Symbol: H. Selenium is the 33rd element of the periodic table. ");
		elements.put("Bromine", "Element Symbol: H. Bromine is the 34th element of the periodic table. ");
		elements.put("Krypton", "Element Symbol: H. Krypton is the 35th element of the periodic table. ");
		elements.put("Rubidium", "Element Symbol: H. Rubidium is the 36th element of the periodic table. ");
		elements.put("Strontium", "Element Symbol: H. Strontium is the 37th element of the periodic table. ");
		elements.put("Yttrium", "Element Symbol: H. Yttrium is the 38th element of the periodic table. ");
		elements.put("Zirconium", "Element Symbol: H. Zirconium is the 39th element of the periodic table. ");
		elements.put("Niobium", "Element Symbol: H. Niobium is the 40th element of the periodic table. ");
		elements.put("Molybdenum", "Element Symbol: H. Molybdenum is the 41st element of the periodic table. ");
		elements.put("Technetium", "Element Symbol: H. Technetium is the 42nd element of the periodic table. ");
		elements.put("Ruthenium", "Element Symbol: H. Ruthenium is the 43rd element of the periodic table. ");
		elements.put("Rhodium", "Element Symbol: H. Rhodium is the first 44th of the periodic table. ");
		elements.put("Palladium", "Element Symbol: H. Palladium is the 45th element of the periodic table. ");
		elements.put("Silver", "Element Symbol: H. Silver is the 46th element of the periodic table. ");
		elements.put("Cadmium", "Element Symbol: H. Cadmium is the 47th element of the periodic table. ");
		elements.put("Indium", "Element Symbol: H. Indium is the 48th element of the periodic table. ");
		elements.put("Tin", "Element Symbol: H. Tin is the 49th element of the periodic table. ");
		elements.put("Antimony", "Element Symbol: H. Antimony is the 50th element of the periodic table. ");
		elements.put("Tellurium", "Element Symbol: H. Tellurium is the 51st element of the periodic table. ");
		elements.put("Iodine", "Element Symbol: H. Iodine is the 52nd element of the periodic table. ");
		elements.put("Xenon", "Element Symbol: H. Xenon is the 53rd element of the periodic table. ");
		elements.put("Cesium", "Element Symbol: H. Cesium is the 54th element of the periodic table. ");
		elements.put("Barium", "Element Symbol: H. Barium is the 55th element of the periodic table. ");
		elements.put("Lanthanum", "Element Symbol: H. Lanthanum is the 56th element of the periodic table. ");
		elements.put("Cerium", "Element Symbol: H. Cerium is the 57th element of the periodic table. ");
		elements.put("Praseodymium", "Element Symbol: H. Praseodymium is the 58th element of the periodic table. ");
		elements.put("Neodymium", "Element Symbol: H. Neodymium is the 59th element of the periodic table. ");
		elements.put("Promethium", "Element Symbol: H. Promethium is the 60th element of the periodic table. ");
		elements.put("Samarium", "Element Symbol: H. Samarium is the 61st element of the periodic table. ");
		elements.put("Europium", "Element Symbol: H. Europium is the 62nd element of the periodic table. ");
		elements.put("Gadolinium", "Element Symbol: H. Gadolinium is the 63rd element of the periodic table. ");
		elements.put("Terbium", "Element Symbol: H. Terbium is the 64th element of the periodic table. ");
		elements.put("Dysprosium", "Element Symbol: H. Dysprosium is the 65th element of the periodic table. ");
		elements.put("Holmium", "Element Symbol: H. Holmium is the 66th element of the periodic table. ");
		elements.put("Erbium", "Element Symbol: H. Erbium is the 67th element of the periodic table. ");
		elements.put("Thulium", "Element Symbol: H. Thulium is the 68th element of the periodic table. ");
		elements.put("Ytterbium", "Element Symbol: H. Ytterbium is the 69th (haha) element of the periodic table. ");
		elements.put("Lutetium", "Element Symbol: H. Lutetium is the 70th element of the periodic table. ");
		elements.put("Hafnium", "Element Symbol: H. Hafnium is the 71st element of the periodic table. ");
		elements.put("Tantalum", "Element Symbol: H. Tantalum is the 72nd element of the periodic table. ");
		elements.put("Tungsten", "Element Symbol: H. Tungsten is the 73rd element of the periodic table. ");
		elements.put("Rhenium", "Element Symbol: H. Rhenium is the 74th element of the periodic table. ");
		elements.put("Osmium", "Element Symbol: H. Osmium is the 75th element of the periodic table. ");
		elements.put("Iridium", "Element Symbol: H. Iridium is the 76th element of the periodic table. ");
		elements.put("Platinum", "Element Symbol: H. Platinum is the 77th element of the periodic table. ");
		elements.put("Gold", "Element Symbol: H. Gold is the 78th element of the periodic table. ");
		elements.put("Mercury", "Element Symbol: H. Mercury is the 79th element of the periodic table. ");
		elements.put("Thallium", "Element Symbol: H. Thallium is the 80th element of the periodic table. ");
		elements.put("Lead", "Element Symbol: H. Lead is the 81st element of the periodic table. ");
		elements.put("Bismuth", "Element Symbol: H. Bismuth is the 82nd element of the periodic table. ");
		elements.put("Polonium", "Element Symbol: H. Polonium is the 83rd element of the periodic table. ");
		elements.put("Astatine", "Element Symbol: H. Astatine is the 84th element of the periodic table. ");
		elements.put("Radon", "Element Symbol: H. Radon is the 85th element of the periodic table. ");
		elements.put("Francium", "Element Symbol: H. Francium is the 86th element of the periodic table. ");
		elements.put("Radium", "Element Symbol: H. Radium is the 87th element of the periodic table. ");
		elements.put("Actinium", "Element Symbol: H. Actinium is the 88th element of the periodic table. ");
		elements.put("Thorium", "Element Symbol: H. Thorium is the 89th element of the periodic table. ");
		elements.put("Protactinium", "Element Symbol: H. Protactinium is the 90th element of the periodic table. ");
		elements.put("Uranium", "Element Symbol: H. Uranium is the 91st element of the periodic table. ");
		elements.put("Neptunium", "Element Symbol: H. Neptunium is the 92nd element of the periodic table. ");
		elements.put("Plutonium", "Element Symbol: H. Plutonium is the 93rd element of the periodic table. ");
		elements.put("Americium", "Element Symbol: H. Americium is the 94th element of the periodic table. ");
		elements.put("Curium", "Element Symbol: H. Curium is the 95th element of the periodic table. ");
		elements.put("Berkelium", "Element Symbol: H. Berkelium is the 96th element of the periodic table. ");
		elements.put("Californium", "Element Symbol: H. Californium is the 97th element of the periodic table. ");
		elements.put("Einsteinium", "Element Symbol: . Einsteinium is the 98th element of the periodic table. ");
		elements.put("Fermium", "Element Symbol: H. Fermium is the 99th element of the periodic table. ");
		elements.put("Mendelevium", "Element Symbol: H. Mendelevium is the 100th element of the periodic table. ");
		elements.put("Nobelium", "Element Symbol: H. Nobelium is the 101st element of the periodic table. ");
		elements.put("Lawrencium", "Element Symbol: H. Lawrencium is the 102nd element of the periodic table. ");
		elements.put("Rutherfordium", "Element Symbol: H. Rutherfordium is the 103rd element of the periodic table. ");
		elements.put("Dubnium", "Element Symbol: H. Dubnium is the 104th element of the periodic table. ");
		elements.put("Seaborgium", "Element Symbol: H. Seaborgium is the 105th element of the periodic table. ");
		elements.put("Bohrium", "Element Symbol: H. Bohrium is the 106th element of the periodic table. ");
		elements.put("Hassium", "Element Symbol: H. Hassium is the 107th element of the periodic table. ");
		elements.put("Meitnerium", "Element Symbol: H. Meitnerium is the 108th element of the periodic table. ");
		elements.put("Darmstadtium", "Element Symbol: H. Darmstadtium is the 109th element of the periodic table. ");
		elements.put("Roentgenium", "Element Symbol: H. Roentgenium is the 110th element of the periodic table. ");
		elements.put("Ununbium", "Element Symbol: H. Ununbium is the first 111th of the periodic table. ");
		elements.put("Ununtrium", "Element Symbol: H. Ununtrium is the 112th element of the periodic table. ");
		elements.put("Ununquadium", "Element Symbol: H. Ununquadium is the 113th element of the periodic table. ");
		elements.put("Ununpentium", "Element Symbol: H. Ununpentium is the 114th element of the periodic table. ");
		elements.put("Ununhexium", "Element Symbol: H. Ununhexium is the 115th element of the periodic table. ");
		elements.put("Ununseptium", "Element Symbol: H. Ununseptium is the 116th element of the periodic table. ");
		elements.put("Ununoctium", "Element Symbol: H. Ununoctium is the 117th element of the periodic table. ");

	}

}
